Pull from sugar-network-sync

diff --git a/sugar-network-sync b/sugar-network-sync
--- a/sugar-network-sync
+++ b/sugar-network-sync
@@ -15,20 +15,25 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-debug() {
-    [ "${V}" ] && echo "-- $@"
-}
+[ "${V}" ] && set -x
 
 info() {
     echo "-- $@"
 }
+
+phase() {
+    echo "   $@"
+}
+
 
 warning() {
     echo "-- $@"
 }
 
 abort() {
-    echo "-- ERROR $@"
+    rm -f *.out
+    echo "-- $@"
+    echo "   run \"V=1 $0 ${cmdline}\" to get full debugging output"
     exit 1
 }
 
@@ -38,7 +43,7 @@ Usage: $(basename $0) [PATH] [URL]
 
 Sugar Network sneakernet synchronization utility.
 
-Arguments:
+Command arguments:
   PATH      if specified, utility will try to recursive search for
             synchronization packet files (files with ".packet" suffix);
             using wget or curl utility, each packet will be uploaded
@@ -49,6 +54,10 @@ Arguments:
             http://api-testing.network.sugarlabs.org; script will download
             full data dump from the server
 
+Utility is intended to upload request packet files (generated by Sugar Network
+node servers) to Sugar Network master server and download response packets
+to deliver them back to nodes.
+
 See http://wiki.sugarlabs.org/go/Sugar_Network for details.
 EOF
 }
@@ -58,59 +67,48 @@ get_header_key() {
     key="$2"
 
     tar -xf "${packet}" header --to-stdout | \
-        grep -o "\"${key}\": *\"[^\"]*\"" | \
-        awk -F\" '{print $4}'
+        grep -o "\"${key}\":[^,}]\+" | \
+        sed 's/^[^:]*://; s/^[ "]*//; s/"$//'
 }
 
 upload() {
-    in_packet="$1"
-    cmd="$2"
-    api_url="$3"
-    if [ -z "${api_url}" ]; then
-        api_url="$(get_header_key "${in_packet}" api_url)"
-        if [ -z "${api_url}" ]; then
-            info "Packet '${in_packet}' is not intended to upload to server, skipped"
-            return 1
-        fi
-    fi
-    url="${api_url}?cmd=${cmd}"
+    url="$1"
+    in_packet="$2"
+    cookie="$3"
     out_packet="${in_packet}.out"
 
-    info "Upload '${in_packet}'"
+    [ -e "${in_packet}" ] || touch "${in_packet}"
     [ -e "${out_packet}" ] && abort "Destination ${out_packet} already exists"
 
     if which wget >/dev/null 2>&1; then
-        cmd="wget --post-file '${in_packet}' '${url}' -O '${out_packet}'"
+        cmd="wget --post-file='${in_packet}' --output-document='${out_packet}' --load-cookies='${cookie}' --save-cookies='${cookie}'"
         [ "${V}" ] || cmd="${cmd} -q"
     else
-        cmd="curl -XPOST --data-binary @'${in_packet}' '${url}' -o '${out_packet}'"
+        cmd="curl -XPOST --data-binary=@'${in_packet}' --output='${out_packet}' --cookie-jar='${cookie}'"
         [ "${V}" ] || cmd="${cmd} -s"
     fi
 
-    debug "Run '${cmd}' upload command"
-    sh -c "$cmd" || abort "Cannot upload using '$cmd' command"
+    sh -c "${cmd} '${url}'" || abort "Cannot run upload command"
+    rm "${in_packet}"
 
     if [ -e "${out_packet}" ]; then
         if [ $(stat -c %s "${out_packet}") -eq 0 ]; then
             rm "${out_packet}"
         else
-            if [ "$(get_header_key "${out_packet}" continue)" = "true" ]; then
-                tar xf "${out_packet}" continue || abort "Cannot exatract 'continue' file"
-                tar uf continue.packet continue || abort "Cannot update 'continue.packet'"
-                rm continue
-            fi
-            [ "$(get_header_key "${out_packet}" empty)" = "true" ] && rm "${out_packet}"
+            out_filename="$(get_header_key "${out_packet}" filename)"
+            phase "Store results in ${out_filename}"
+            mv "${out_packet}" "${out_filename}" || abort "Cannot write ${out_filename}"
         fi
     fi
 
-    info "Remove uploaded '${in_packet}' packet"
-    rm "${in_packet}"
-
-    if [ -e "${out_packet}" ]; then
-        out_filename="$(get_header_key "${out_packet}" filename)"
-        [ "${out_filename}" ] || out_filename="${in_packet}"
-        info "Store resulting packet in '${out_filename}'"
-        mv "${out_packet}" "${out_filename}" || abort
+    if [ -e "${cookie}" ]; then
+        if grep sn_pull_unset "${cookie}" >/dev/null; then
+            rm "${cookie}"
+        elif grep sn_pull "${cookie}" >/dev/null; then
+            phase "Postpone pull with ${cookie}"
+        else
+            rm "${cookie}"
+        fi
     fi
 }
 
@@ -121,19 +119,42 @@ fi
 
 sync_path="$1"
 clone_url="$2"
+cmdline="$@"
 FS=
 
-cd "${sync_path}" || abort "Cannot cd to '${sync_path}' sync directory"
-
-# Push packet and collect "continue.packet" to pull afterwards
-for packet in $(find . -name '*.packet' -a ! -name 'continue.packet'); do
-    upload "${packet}" pull || continue
-done
+cd "${sync_path}" || abort "Cannot switch to ${sync_path} sync directory"
 
 if [ "${clone_url}" ]; then
-    info "Clone initial server dump from ${clone_url}"
-    in_packet="clone.packet"
-    [ -e ${in_packet} ] && abort "Destination ${in_packet} already exists"
-    touch ${in_packet}
-    upload ${in_packet} pull "${clone_url}"
+    info "Clone initial master dump"
+    upload "${clone_url}?cmd=pull" clone.out
+    exit 0
 fi
+
+# Push packet and collect "continue.packet" to pull afterwards
+for packet in $(find -type f -name '*.packet'); do
+    api_url="$(get_header_key "${packet}" api_url)"
+    if [ -z "${api_url}" ]; then
+        info "Skip ${packet}, it is not intended for uploading"
+    else
+        info "Push ${packet} to ${api_url}"
+        hostname="$(echo "${api_url}" | awk -F/ '{print $3}')"
+        upload "${api_url}?cmd=push" "${packet}" "${hostname}.cookie"
+    fi
+done
+
+limit=$(expr 1024 \* 1024 \* 10)
+while true; do
+    found=
+    for cookie in $(find -type f -name '*.cookie'); do
+        disk_free=$(df . --block-size=1 | tail -n1 | awk '{print $4}')
+        [ $disk_free -gt $limit ] || abort \
+            "No free disk space on $PWD, copy all *.cookie files" \
+            "to directory with more free space and re-run $0 from there"
+
+        api_url="http://$(basename "${cookie}" .cookie)"
+        info "Pull updates from ${api_url}"
+        upload "${api_url}?cmd=pull" pull.out "${cookie}"
+        found=1
+    done
+    [ "${found}" ] || break
+done
