Fix basic client routes

diff --git a/sugar-network-sync b/sugar-network-sync
--- a/sugar-network-sync
+++ b/sugar-network-sync
@@ -17,6 +17,8 @@
 
 [ "${V}" ] && set -x
 
+PARCEL_SUFFIX=".parcel"
+
 info() {
     echo "-- $@"
 }
@@ -45,18 +47,18 @@ Sugar Network sneakernet synchronization utility.
 
 Command arguments:
   PATH      if specified, utility will try to recursively search for
-            synchronization packet files (files with ".sneakernet" suffix);
+            synchronization packet files (files with "$PARCEL_SUFFIX" suffix);
             using wget or curl utility, each file will be uploaded
             to the targeting Sugar Network server with downloading resulting
             packets; on success, uploaded packets will be removed and resulting
             packets will be placed to PATH instead
   URL       if specified, should be Sugar Network API url, e.g.,
-            http://api-testing.network.sugarlabs.org; script will download
-            full data dump from the server
+            http://node.sugarlabs.org; instead of synchronization, the script
+            will download full data dump from the specified master node
 
 Utility is intended to upload request packet files (generated by Sugar Network
-node servers) to Sugar Network master server and download response packets
-to deliver them back to nodes.
+slave node) to Sugar Network master server and download response packets
+to deliver them back to slave.
 
 See http://wiki.sugarlabs.org/go/Sugar_Network for details.
 EOF
@@ -99,9 +101,14 @@ upload() {
         if [ $(stat -c %s "${out_packet}") -eq 0 ]; then
             rm "${out_packet}"
         else
-            out_filename="$(get_header_key "${out_packet}" filename)"
-            phase "Store results in ${out_filename}"
-            mv "${out_packet}" "${out_filename}" || abort "Cannot write ${out_filename}"
+            if [ "${in_packet}" ]; then
+                phase "Replace ${in_packet} with results"
+                mv "${out_packet}" "${in_packet}" || abort "Cannot write to ${in_packet}"
+            else
+                out_filename="$(get_hostname $url)"$PARCEL_SUFFIX
+                phase "Store results in ${out_filename}"
+                mv "${out_packet}" "${out_filename}" || abort "Cannot write to ${out_filename}"
+            fi
         fi
     fi
 
@@ -174,13 +181,13 @@ if [ "${clone_url}" ]; then
 fi
 
 # Upload push packets at first
-for package in $(find -type f -name '*.sneakernet' -printf '%f\n'); do
-    api_url="$(get_header_key "${package}" api_url)"
+for parcel in $(find -type f -name "*$PARCEL_SUFFIX" -printf '%f\n'); do
+    api_url="$(get_header_key "${parcel}" api_url)"
     if [ -z "${api_url}" ]; then
-        info "Skip ${package}, it is not intended for uploading"
+        info "Skip ${parcel}, it is not intended for uploading"
     else
-        info "Push ${package} to ${api_url}"
-        upload "${api_url}?cmd=push" "$(get_hostname ${api_url}).cookie" "${package}"
+        info "Push ${parcel} to ${api_url}"
+        upload "${api_url}?cmd=push" "$(get_hostname ${api_url}).cookie" "${parcel}"
     fi
 done
 
